--border sharp
--list-border sharp
--input-border sharp
--header-border sharp
--preview-border sharp
--height 40%
--layout reverse
--scroll-off=200
--padding 1,2
--border-label 'fzf'
--input-label 'Input'
--header-label 'File Type'
--preview '/home/tx27/.config/fzf/fzf-preview.sh {}'
--bind 'result:transform-list-label:
if [[ -z  ]]; then
echo "  items ";
else echo "  matches for [] ";
fi'
--bind 'focus:transform-preview-label:[[ -n {} ]] && printf " Previewing [%s] " {}'
--bind 'focus:+transform-header:file --brief {} || echo "No file selected"'
--bind 'ctrl-r:change-list-label(Reloading the list)+reload(sleep 2; git ls-files)'
