save-position-on-quit=yes
keep-open=yes
alang=pl,pol,en,eng
slang=pl,pol,en,eng

vo=gpu
gpu-context=wayland
gpu-api=opengl

hwdec=vaapi-copy
hwdec-codecs=all

profile=fast
vd-lavc-threads=0

video-sync=display-resample
interpolation=no

cache=yes
demuxer-max-bytes=2G
demuxer-max-back-bytes=1G

scale=bilinear
cscale=bilinear
dscale=bilinear
