general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock --grace 10      # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 200                                # 2.5min.
    on-timeout = hyprctl hyprsunset gamma 40     # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = hyprctl hyprsunset gamma 100     # monitor backlight restore.
}

# nie działa bez sudo na razie :(
# listener { 
#     timeout = 15                                          # 2.5min.
#     on-timeout = bash -sh "echo 0 | tee /sys/class/leds/tpacpi::kbd_backlight/brightness"   # turn off keyboard backlight.
# }

listener {
    timeout = 300                                 # 5min
    on-timeout = hyprlock --grace 5               # lock screen when timeout has passed
}

listener {
    timeout = 310                                                                # 5min
    on-timeout = hyprctl dispatch dpms off                                       # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && hyprctl hyprsunset gamma 100         # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 9000                                # 15min
    on-timeout = systemctl suspend                # suspend pc
}
