gesture swipe left     3    i3-msg workspace next
gesture swipe right    3    i3-msg workspace prev
gesture swipe up       3    ~/.config/rofi/launcher.sh
gesture swipe down     3    xdotool key Escape

gesture swipe down     4    pamixer -d 5
gesture swipe up       4    pamixer -i 5
gesture swipe left     4    playerctl next
gesture swipe right    4    playerctl previous
gesture hold  on       4    playerctl play-pause
