#################################
# Backend
#################################
backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
detect-client-opacity = true;
log-level = "warn";
log-file = "/dev/null";
unredir-if-possible = false;

#################################
# Shadows
#################################
shadow = true;
shadow-radius   = 18;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.3;
shadow-ignore-shaped = false;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'rofi'",
  "class_g = 'Dunst'",
  "_GTK_FRAME_EXTENTS@:c"
];


#################################
# Opacity
#################################
inactive-opacity = 0.92;
active-opacity = 0.98;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "95:class_g = 'code-oss'",
  "90:class_g = 'Thunar'",
  "90:class_g = 'Nautilus'",
  "85:class_g = 'rofi'",
  "85:class_g = 'Dunst'",
  "80:class_g = 'Polybar'"
];

#################################
# Blur
#################################
blur-method = "dual_kawase";
blur-strength = 7;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

blur-kern = "7x7box";

blur-background-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'Dunst'",
  "class_g = 'slop'",
  "class_g = 'Polybar'",
  "window_type = 'dock'"
];

#################################
# Animations
#################################
animations = true;
animation-stiffness = 200;
animation-dampening = 25;

transition-length = 60
transition-pow-x = 0.25
transition-pow-y = 0.25
transition-pow-w = 0.2
transition-pow-h = 0.2

wintypes: {
  tooltip = { fade = false; shadow = false; opacity = 0.9; };
  popup_menu = { fade = false; shadow = false; opacity = 0.9; };
  dropdown_menu = { fade = false; shadow = false; opacity = 0.9; };
  notification = { fade = false; shadow = false; opacity = 0.95; };
}

#################################
# Fading
#################################
fading = true;
fade-delta = 10;
fade-in-step  = 0.05
fade-out-step = 0.04
no-fading-openclose = true;

fade-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'Dunst'",
  "name = 'Notification'",
  "window_type = 'popup_menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'tooltip'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'"
];

#################################
# Corner radius
#################################
rounded-corners = true;
corner-radius = 8;
clip-shadow-above = true;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Rofi'",
  "_GTK_FRAME_EXTENTS@:c"
];


#################################
# Other
#################################
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-transient = true;
detect-client-leader = true;
resize-damage = 1;

#################################
# Workarounds
#################################
xrender-sync-fence = true;
